### List all books

GET http://localhost:8080/api/books

### Get book by title

GET http://localhost:8080/api/books/book_222

### Create book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "batata batata",
  "author": "Noam Chomski",
  "numberOfPages": 57
}

### Create invalid book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "",
  "author": "Noam Chomski",
  "numberOfPages": 57
}

### Create invalid Firas
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Title",
  "author": "Firas",
  "numberOfPages": 57
}

### Delete book by title
//DELETE http://localhost:8080/api/books/My_Lovely_Book
//DELETE http://localhost:8080/api/books/book_2
DELETE http://localhost:8080/api/books/Look_Away